### ISSUE TITLE
Location off shows no results or map

### ISSUE THREAD

**Issue by JjoeH** [frank-borkin/ga-pg#10]
Error on load and then no results or map load, filters do nothing. No way to refresh. Should as to turn on location or ask you to manually add them
![screenshot_20151014-113036](https://cloud.githubusercontent.com/assets/15122318/10481285/98de11e8-7267-11e5-991b-f2575f4bfa97.png)
![screenshot_20151014-113045](https://cloud.githubusercontent.com/assets/15122318/10481288/a5d30b38-7267-11e5-8765-f5ceaf221d59.png)

**Comment by frank-borkin** [comment]
Fixed in v0.0.9 - if there's no GPS / fine location it will now use coarse location to get somewhere close.
